### ISSUE TITLE
program works ?

### ISSUE THREAD

**Issue by An1an1** [sambhavmattoo/Nonce_Range_DSA_Crack#1]
Could you tell me in detail how to run the Nonce_Range script correctly? The script calculates the range K ?

**Comment by sambhavmattoo** [comment]
> 

Have a look at the Input json. Substitute the values in it with what you have, so long as it is within the scope of the problem as specified the the pdf. Change the name with which it opens the json in source.py if needed. Run source.json using a python interpreter. Yes, it calculates k, because that itself is constrained in the given problem.

**Comment by An1an1** [comment]
what do the values p,q,g,m,h,y,r,s mean ?
